FROM alpine

# Install shell tools
RUN apk add jq

# Copy the jq-render script
COPY ./jq-render /usr/bin/jq-render

# Prepare the resources for our service
RUN mkdir /service
WORKDIR /service

COPY ./init_container.sh ./server.sh ./settings.json.jq ./
CMD ./init_container.sh
